name: 'Multi-repo milestones.'
description: 'Distribute the milestones from a repository to other repositories.'
inputs:
  repositories:
    description: 'Comma delimited list of repositories to synchronise.'
    required: true
  token:
    description: 'Token with access to repositories you wish to sync'
    required: true
  
runs:
  using: 'node16'
  main: 'dist/index.js'
